export AVM_CROSS_COMPILE=/home/averma/kernel/toolchain/bin/aarch64-linux-android-
export AVM_CLANG_TRIPLE=aarch64-linux-gnu-
export AVM_REAL_CC=/home/averma/kernel/samsung/clang_llvm-10.0.0/bin/clang
export AVM_KERNEL_MAKE_ENV="DTC_EXT=`pwd`/tools/dtc CONFIG_BUILD_ARM64_DT_OVERLAY=y"
export AVM_EXTRA_CFLAGS="-Wno-unused-const-variable -Wno-strict-prototypes"
export AVM_BUILD_KERNEL_LOG_FILE=avm_build_kernel.log
export AVM_ARCH=arm64
export AVM_CONFIG_FILE=a70q_sea_open_defconfig
export AVM_BUILD_REDIRECT=" \| tee -a ${AVM_BUILD_KERNEL_LOG_FILE} 2>&1"


export AVM_MAKE_CONFIG_ARGS="$KERNEL_MAKE_ENV ARCH=$AVM_ARCH REAL_CC=$AVM_REAL_CC CROSS_COMPILE=$AVM_CROSS_COMPILE LLVM=1 CLANG_TRIPLE=$AVM_CLANG_TRIPLE"

export AVM_MAKE_BUILD_ARGS="$KERNEL_MAKE_ENV ARCH=$AVM_ARCH REAL_CC=$AVM_REAL_CC CROSS_COMPILE=$AVM_CROSS_COMPILE LLVM=1 CLANG_TRIPLE=$AVM_CLANG_TRIPLE EXTRA_CFLAGS=${AVM_EXTRA_CFLAGS}"

header()
{

	mv ${AVM_BUILD_KERNEL_LOG_FILE} ${AVM_BUILD_KERNEL_LOG_FILE}.old > /dev/null 2>&1 

	echo "Build Start Time: " >> ${AVM_BUILD_KERNEL_LOG_FILE}
	echo "`date`" >> ${AVM_BUILD_KERNEL_LOG_FILE}
	echo "" >> ${AVM_BUILD_KERNEL_LOG_FILE}

	echo "AVM_CROSS_COMPILE=$AVM_CROSS_COMPILE" >> ${AVM_BUILD_KERNEL_LOG_FILE}
	echo "" >> ${AVM_BUILD_KERNEL_LOG_FILE}

	echo "AVM_CLANG_TRIPLE=$AVM_CLANG_TRIPLE" >> ${AVM_BUILD_KERNEL_LOG_FILE}
	echo "" >> ${AVM_BUILD_KERNEL_LOG_FILE}

	echo "AVM_REAL_CC=$AVM_REAL_CC" >> ${AVM_BUILD_KERNEL_LOG_FILE}
	echo "" >> ${AVM_BUILD_KERNEL_LOG_FILE}

	echo "AVM_ARCH=$AVM_ARCH" >> ${AVM_BUILD_KERNEL_LOG_FILE}
	echo "" >> ${AVM_BUILD_KERNEL_LOG_FILE}

	echo "AVM_KERNEL_MAKE_ENV=$AVM_KERNEL_MAKE_ENV" >> ${AVM_BUILD_KERNEL_LOG_FILE}
	echo "" >> ${AVM_BUILD_KERNEL_LOG_FILE}

	echo "AVM_MAKE_CONFIG_ARGS=$AVM_MAKE_CONFIG_ARGS" >> ${AVM_BUILD_KERNEL_LOG_FILE}
	echo "" >> ${AVM_BUILD_KERNEL_LOG_FILE}

	echo "AVM_MAKE_BUILD_ARGS=$AVM_MAKE_BUILD_ARGS" >> ${AVM_BUILD_KERNEL_LOG_FILE}
	echo "" >> ${AVM_BUILD_KERNEL_LOG_FILE}
}

footer()
{
	echo "" >> ${AVM_BUILD_KERNEL_LOG_FILE}
	echo "Build End Time: " >> ${AVM_BUILD_KERNEL_LOG_FILE}
	echo "`date`" >> ${AVM_BUILD_KERNEL_LOG_FILE}

	echo "Log file for build logs: "${AVM_BUILD_KERNEL_LOG_FILE}

}

main_make()
{
	time make V=1 -C `pwd` $AVM_MAKE_CONFIG_ARGS $AVM_CONFIG_FILE
	time make V=1 -j2 -C `pwd` $AVM_MAKE_BUILD_ARGS | tee -a ${AVM_BUILD_KERNEL_LOG_FILE} 2>&1
}

header
main_make
footer

